services:
  fancyindex:
    restart: always
    container_name: cinema_files
    build:
      dockerfile: Dockerfile
    ports:
      - "8180:80"
    volumes:
      - "/mnt/p300_3tb/cinema:/usr/local/nginx"
